sudo RUST_BACKTRACE=full /home/ubuntu/diet-rpc-validator/target/release/solana-validator \
  --identity ./test-keypair.json \
  --vote-account ./test-keypair.json \
  --rpc-port 8891 \
  --entrypoint entrypoint.testnet.solana.com:8001 \
  --limit-ledger-size \
  --no-voting \
  --no-os-network-limits-test \
  --minimal-snapshot-download-speed 100000000 \
  --skip-poh-verify \
  --no-poh-speed-test \
  --full-rpc-api \
  --enable-rpc-transaction-history \
  --log /home/ubuntu/diet-rpc-validator/solana-validator.log \
  --accounts /mnt/accounts \
  --ledger /mnt/ledger \
  --snapshots /mnt/snapshots
